-- AlterTable: Optimize string columns from TEXT to VARCHAR with appropriate lengths

-- User table
ALTER TABLE "User" ALTER COLUMN "id" SET DATA TYPE VARCHAR(32);
ALTER TABLE "User" ALTER COLUMN "email" SET DATA TYPE VARCHAR(255);
ALTER TABLE "User" ALTER COLUMN "passwordHash" SET DATA TYPE VARCHAR(60);
ALTER TABLE "User" ALTER COLUMN "name" SET DATA TYPE VARCHAR(255);

-- Session table
ALTER TABLE "Session" ALTER COLUMN "id" SET DATA TYPE VARCHAR(32);
ALTER TABLE "Session" ALTER COLUMN "userId" SET DATA TYPE VARCHAR(32);
ALTER TABLE "Session" ALTER COLUMN "tokenHash" SET DATA TYPE VARCHAR(64);

-- Medication table
ALTER TABLE "Medication" ALTER COLUMN "id" SET DATA TYPE VARCHAR(32);
ALTER TABLE "Medication" ALTER COLUMN "userId" SET DATA TYPE VARCHAR(32);
ALTER TABLE "Medication" ALTER COLUMN "name" SET DATA TYPE VARCHAR(150);
ALTER TABLE "Medication" ALTER COLUMN "dose" SET DATA TYPE VARCHAR(100);

-- ScheduleEntry table
ALTER TABLE "ScheduleEntry" ALTER COLUMN "id" SET DATA TYPE VARCHAR(32);
ALTER TABLE "ScheduleEntry" ALTER COLUMN "medicationId" SET DATA TYPE VARCHAR(32);
ALTER TABLE "ScheduleEntry" ALTER COLUMN "userId" SET DATA TYPE VARCHAR(32);